### ISSUE TITLE
Unable To Run Starter Code 

### ISSUE THREAD

**Issue by eyucherin** [UMass-Foundation-Model/HAZARD#4]
Hello! I was able to  install ThreeDWorld and follow the installation instructions for this project but when I run the `starter_code.py` I get the following error 

```
(base) che@che-MS-7D99:~/Desktop/HAZARD$ python starter_code.py
/home/che/.local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
/home/che/.local/lib/python3.8/site-packages/mmengine/model/utils.py:137: UserWarning: Cannot import torch.fx, `merge_dict` is a simple function to merge multiple dicts
  warnings.warn('Cannot import torch.fx, `merge_dict` is a simple function '
Traceback (most recent call last):
  File "starter_code.py", line 1, in <module>
    from HAZARD import submit
  File "/home/che/.local/lib/python3.8/site-packages/HAZARD/__init__.py", line 1, in <module>
    from .run_experiments import submit
  File "/home/che/.local/lib/python3.8/site-packages/HAZARD/run_experiments.py", line 1, in <module>
    from src.HAZARD.challenge import Challenge, init_logs
  File "/home/che/Desktop/HAZARD/src/HAZARD/__init__.py", line 1, in <module>
    from .run_experiments import submit
  File "/home/che/Desktop/HAZARD/src/HAZARD/run_experiments.py", line 1, in <module>
    from src.HAZARD.challenge import Challenge, init_logs
  File "/home/che/Desktop/HAZARD/src/HAZARD/challenge.py", line 8, in <module>
    from .envs.wind import WindEnv
  File "/home/che/Desktop/HAZARD/src/HAZARD/envs/wind/__init__.py", line 2, in <module>
    from .wind_gym import WindEnv
  File "/home/che/Desktop/HAZARD/src/HAZARD/envs/wind/wind_gym.py", line 5, in <module>
    from .windagent_controller import *
  File "/home/che/Desktop/HAZARD/src/HAZARD/envs/wind/windagent_controller.py", line 2, in <module>
    from envs.wind.object import ObjectStatus
ModuleNotFoundError: No module named 'envs.wind'
```

Any insight or help on this would be greatly appreciated!

**Comment by zhouqqhh** [comment]
Hi! It seems to be a import bug from the latest push, and we just fixed this bug. Sorry for the inconvenience .

**Comment by eyucherin** [comment]
Hi it seems like the ModuleNotFoundError for `envs.wind` was fixed but now I am getting a new ModuleNotFoundError 

```
(base) che@che-MS-7D99:~/Desktop/HAZARD$ python3 starter_code.py 
/home/che/.local/lib/python3.8/site-packages/mmengine/model/utils.py:137: UserWarning: Cannot import torch.fx, `merge_dict` is a simple function to merge multiple dicts
  warnings.warn('Cannot import torch.fx, `merge_dict` is a simple function '
Traceback (most recent call last):
  File "starter_code.py", line 1, in <module>
    from HAZARD import submit
  File "/home/che/Desktop/HAZARD/src/HAZARD/__init__.py", line 1, in <module>
    from .run_experiments import submit
  File "/home/che/Desktop/HAZARD/src/HAZARD/run_experiments.py", line 1, in <module>
    from src.HAZARD.challenge import Challenge, init_logs
  File "/home/che/Desktop/HAZARD/src/HAZARD/__init__.py", line 1, in <module>
    from .run_experiments import submit
  File "/home/che/Desktop/HAZARD/src/HAZARD/run_experiments.py", line 14, in <module>
    from policy.oracal import OracleAgent
  File "/home/che/Desktop/HAZARD/src/HAZARD/policy/oracal.py", line 7, in <module>
    from envs.flood.utils import ObjectState as FloodObjectState
ModuleNotFoundError: No module named 'envs.flood'
```

Would this also be a bug?

**Comment by zhouqqhh** [comment]
Hi we suggest you export HAZARD to the PYTHONPATH as in the newest document (https://github.com/UMass-Foundation-Model/HAZARD/blob/e8d044ff2133443009b11696a8b3bb35543e3d8b/documentation/get_started/install.md?plain=1#L33)

**Comment by eyucherin** [comment]
It seems like the issue still persists even after exporting to the PYTHONPATH 

```
(base) che@che-MS-7D99:~/Desktop/HAZARD$ export PYTHONPATH=$PYTHONPATH:/home/che/Desktop/HAZARD
```
```
(base) che@che-MS-7D99:~/Desktop/HAZARD$ python3 starter_code.py
/home/che/.local/lib/python3.8/site-packages/mmengine/model/utils.py:137: UserWarning: Cannot import torch.fx, `merge_dict` is a simple function to merge multiple dicts
  warnings.warn('Cannot import torch.fx, `merge_dict` is a simple function '
Traceback (most recent call last):
  File "starter_code.py", line 1, in <module>
    from HAZARD import submit
  File "/home/che/Desktop/HAZARD/src/HAZARD/__init__.py", line 1, in <module>
    from .run_experiments import submit
  File "/home/che/Desktop/HAZARD/src/HAZARD/run_experiments.py", line 1, in <module>
    from src.HAZARD.challenge import Challenge, init_logs
  File "/home/che/Desktop/HAZARD/src/HAZARD/__init__.py", line 1, in <module>
    from .run_experiments import submit
  File "/home/che/Desktop/HAZARD/src/HAZARD/run_experiments.py", line 14, in <module>
    from policy.oracal import OracleAgent
  File "/home/che/Desktop/HAZARD/src/HAZARD/policy/oracal.py", line 7, in <module>
    from envs.flood.utils import ObjectState as FloodObjectState
ModuleNotFoundError: No module named 'envs.flood'

```

**Comment by AmpiroMax** [comment]
> Hi it seems like the ModuleNotFoundError for `envs.wind` was fixed but now I am getting a new ModuleNotFoundError for `envs.flood`
> 
> ```
> (base) che@che-MS-7D99:~/Desktop/HAZARD$ python3 starter_code.py 
> /home/che/.local/lib/python3.8/site-packages/mmengine/model/utils.py:137: UserWarning: Cannot import torch.fx, `merge_dict` is a simple function to merge multiple dicts
>   warnings.warn('Cannot import torch.fx, `merge_dict` is a simple function '
> Traceback (most recent call last):
>   File "starter_code.py", line 1, in <module>
>     from HAZARD import submit
>   File "/home/che/Desktop/HAZARD/src/HAZARD/__init__.py", line 1, in <module>
>     from .run_experiments import submit
>   File "/home/che/Desktop/HAZARD/src/HAZARD/run_experiments.py", line 1, in <module>
>     from src.HAZARD.challenge import Challenge, init_logs
>   File "/home/che/Desktop/HAZARD/src/HAZARD/__init__.py", line 1, in <module>
>     from .run_experiments import submit
>   File "/home/che/Desktop/HAZARD/src/HAZARD/run_experiments.py", line 14, in <module>
>     from policy.oracal import OracleAgent
>   File "/home/che/Desktop/HAZARD/src/HAZARD/policy/oracal.py", line 7, in <module>
>     from envs.flood.utils import ObjectState as FloodObjectState
> ModuleNotFoundError: No module named 'envs.flood'
> ```
> 
> Would this also be a bug?

I have encountered the same bug. Are there any updates on it?
